<?php
$location_shimotokida = array();
$people = array();
$random_spawn_shimotokida = array();
$db_population_uda_2015_m = array();
$db_population_uda_2015_w = array();
$db_population_tamaru_2015_m = array();
$db_population_tamaru_2015_w = array();
$db_population_tokida_2015_m = array();
$db_population_tokida_2015_w = array();
$db_population_shimotokida_2015_m = array();
$db_population_shimotokida_2015_w = array();
$db_population_uda_2020_m = array();
$db_population_uda_2020_w = array();
$db_population_tamaru_2020_m = array();
$db_population_tamaru_2020_w = array();
$db_population_tokida_2020_m = array();
$db_population_tokida_2020_w = array();
$db_population_shimotokida_2020_m = array();
$db_population_shimotokida_2020_w = array();
$db_population_uda_2025_m = array();
$db_population_uda_2025_w = array();
$db_population_tamaru_2025_m = array();
$db_population_tamaru_2025_w = array();
$db_population_tokida_2025_m = array();
$db_population_tokida_2025_w = array();
$db_population_shimotokida_2025_m = array();
$db_population_shimotokida_2025_w = array();
$db_population_uda_2030_m = array();
$db_population_uda_2030_w = array();
$db_population_tamaru_2030_m = array();
$db_population_tamaru_2030_w = array();
$db_population_tokida_2030_m = array();
$db_population_tokida_2030_w = array();
$db_population_shimotokida_2030_m = array();
$db_population_shimotokida_2030_w = array();
$db_population_uda_2035_m = array();
$db_population_uda_2035_w = array();
$db_population_tamaru_2035_m = array();
$db_population_tamaru_2035_w = array();
$db_population_tokida_2035_m = array();
$db_population_tokida_2035_w = array();
$db_population_shimotokida_2035_m = array();
$db_population_shimotokida_2035_w = array();

try
{
   $db = new PDO(PDO_DSN, DB_USERNAME, DB_PASSWORD);
   $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);


   $stmt = $db->query("SELECT * FROM location_shimotokida");
   $location_shimotokida = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM people");
   $people = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2015 AND `area`='有田' AND `sex`='男' ");
   $db_population_uda_2015_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2015 AND `area`='有田' AND `sex`='女' ");
   $db_population_uda_2015_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2015 AND `area`='田丸' AND `sex`='男' ");
   $db_population_tamaru_2015_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2015 AND `area`='田丸' AND `sex`='女' ");
   $db_population_tamaru_2015_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2015 AND `area`='外城田' AND `sex`='男' ");
   $db_population_tokida_2015_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2015 AND `area`='外城田' AND `sex`='女' ");
   $db_population_tokida_2015_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2015 AND `area`='下外城田' AND `sex`='男' ");
   $db_population_shimotokida_2015_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2015 AND `area`='下外城田' AND `sex`='女' ");
   $db_population_shimotokida_2015_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2020 AND `area`='有田' AND `sex`='男' ");
   $db_population_uda_2020_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2020 AND `area`='有田' AND `sex`='女' ");
   $db_population_uda_2020_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2020 AND `area`='田丸' AND `sex`='男' ");
   $db_population_tamaru_2020_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2020 AND `area`='田丸' AND `sex`='女' ");
   $db_population_tamaru_2020_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2020 AND `area`='外城田' AND `sex`='男' ");
   $db_population_tokida_2020_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2020 AND `area`='外城田' AND `sex`='女' ");
   $db_population_tokida_2020_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2020 AND `area`='下外城田' AND `sex`='男' ");
   $db_population_shimotokida_2020_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2020 AND `area`='下外城田' AND `sex`='女' ");
   $db_population_shimotokida_2020_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2025 AND `area`='有田' AND `sex`='男' ");
   $db_population_uda_2025_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2025 AND `area`='有田' AND `sex`='女' ");
   $db_population_uda_2025_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2025 AND `area`='田丸' AND `sex`='男' ");
   $db_population_tamaru_2025_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2025 AND `area`='田丸' AND `sex`='女' ");
   $db_population_tamaru_2025_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2025 AND `area`='外城田' AND `sex`='男' ");
   $db_population_tokida_2025_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2025 AND `area`='外城田' AND `sex`='女' ");
   $db_population_tokida_2025_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2025 AND `area`='下外城田' AND `sex`='男' ");
   $db_population_shimotokida_2025_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2025 AND `area`='下外城田' AND `sex`='女' ");
   $db_population_shimotokida_2025_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2030 AND `area`='有田' AND `sex`='男' ");
   $db_population_uda_2030_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2030 AND `area`='有田' AND `sex`='女' ");
   $db_population_uda_2030_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2030 AND `area`='田丸' AND `sex`='男' ");
   $db_population_tamaru_2030_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2030 AND `area`='田丸' AND `sex`='女' ");
   $db_population_tamaru_2030_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2030 AND `area`='外城田' AND `sex`='男' ");
   $db_population_tokida_2030_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2030 AND `area`='外城田' AND `sex`='女' ");
   $db_population_tokida_2030_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2030 AND `area`='下外城田' AND `sex`='男' ");
   $db_population_shimotokida_2030_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2030 AND `area`='下外城田' AND `sex`='女' ");
   $db_population_shimotokida_2030_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2035 AND `area`='有田' AND `sex`='男' ");
   $db_population_uda_2035_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2035 AND `area`='有田' AND `sex`='女' ");
   $db_population_uda_2035_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2035 AND `area`='田丸' AND `sex`='男' ");
   $db_population_tamaru_2035_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2035 AND `area`='田丸' AND `sex`='女' ");
   $db_population_tamaru_2035_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2035 AND `area`='外城田' AND `sex`='男' ");
   $db_population_tokida_2035_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2035 AND `area`='外城田' AND `sex`='女' ");
   $db_population_tokida_2035_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2035 AND `area`='下外城田' AND `sex`='男' ");
   $db_population_shimotokida_2035_m = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $stmt = $db->query("SELECT * FROM population WHERE `year`=2035 AND `area`='下外城田' AND `sex`='女' ");
   $db_population_shimotokida_2035_w = $stmt->fetchAll(PDO::FETCH_ASSOC);
   $db = null;
}
catch(PDOException $e)
{
 echo $e->getMessage();
 exit;
}
?>
